image: phusion/passenger-full
script:
  - sudo apt-get update
  - npm config set loglevel warn
  - npm install
  - npm test
deploy:
  git:
    target: dokku@itea.md:maestroo
    branch: master
    force: true
