INSERT INTO user (UserId, Name, FacebookId ) VALUES ('1', 'Henrik Landgren', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('2', 'Carl-Mikael', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('3', 'Administrator', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('4', 'Magnus Johanson', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('5', 'Magnus Tjerneld', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('6', 'MAESTROAGENT', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('7', 'iteam-admin', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('8', 'mau', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('9', 'iteamguest', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('10', 'Henrik Landgren', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('11', 'scout', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('12', 'Christian Landgren', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('13', 'MAESTRO', '154112144637878');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('14', 'Carl-Mikael Lindgren', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('15', 'Lasse Johannesson', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('16', 'MAESTRO MOBILE', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('17', 'Christian Landgren', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('18', 'MAESTRO PAIR', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('19', 'Anders Bornholm', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('20', 'Erik Hjortsberg', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('21', 'man', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('22', 'Tommy Söderström', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('23', 'Fel user', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('24', '', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('25', 'iteam', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('26', 'Emil Brynielsson', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('27', 'matse', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('28', 'ITEAMcln', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('29', 'iteam', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('30', 'emilbr', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('31', 'matse', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('32', 'annsu', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('33', 'susannevz', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('34', 'anderssj', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('35', 'sanapa', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('36', 'karinpe', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('37', 'tobiasgy', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('38', 'mariasa', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('39', 'birgittaed', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('40', 'annagun', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('41', 'Elinwestin', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('42', 'fredrikpa', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('43', 'martinhe', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('44', 'annath', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('45', 'nilshe', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('46', 'karinlun', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('47', 'charlottala', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('48', 'tomasinede', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('49', 'marianneah', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('50', 'Administrator', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('51', 'johanda', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('52', 'carinlem', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('53', 'Mats Egardt', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('54', 'marialiv', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('55', 'charlottemo', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('56', 'gäst', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('57', 'mikaelth', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('58', 'ITEAM/mtj', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('59', 'cmr', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('60', 'pli', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('61', 'Caroline Tamber', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('62', 'Rasmus Fredriksson', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('63', 'Ola Wallin', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('64', 'iteam-guest', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('65', 'mjo', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('66', 'cri', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('68', 'Johanna Gustafsson', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('70', 'Hans Rollman', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('71', 'Sebastian Nilsson', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('72', 'Christian Landgren', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('75', 'Christian Landgren', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('76', 'Henrik Landgren', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('78', 'Johanna Gustafsson', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('79', 'Caroline Tamber', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('80', 'Rasmus Fredriksson', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('81', 'Mats Egardt', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('82', 'carolinetamber', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('83', 'iteamsolutions', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('84', 'Christian Landgren', '695078938');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('85', 'Rasmus Fredriksson', '100001964317440');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('86', 'Mats Egardt', '594216665');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('87', 'Tommy Söderström', '697328335');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('88', 'Daniel Stridsberg', '569295764');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('89', 'Caroline Tamber', '670066108');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('90', 'Henrik Landgren', '731965183');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('91', 'Johanna Johansson', '710375827');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('92', 'Magnus Tjerneld', '583433135');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('93', 'Jakob Ehn', '1528849406');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('94', 'Johanna Gustafsson','578981361');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('95', 'Anders Bornholm', '661413419');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('96', 'Hans Rollman', '569520869');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('97', 'Oscar Månsson', '692163973');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('98', 'Sebastian Nilsson', '606105932');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('99', 'Ola Wallin', '593041723');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('123', 'Pontus Hymér', '725611898');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('124', 'Maria Sölscher', '606905644');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('125', 'Thea Tyvi', '687097891');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('126', 'Robert Johansson', '618486855');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('127', 'Johan Landgren', '649902340');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('128', 'Andreas Krohn', '724416803');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('129', 'Maestroo', NULL);
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('130', 'Martin Wahlund', '551734407');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('131', 'Robin Salazar', '530255539');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('132', 'Maria Bomberg', '701105995');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('133', 'Johan Öbrink', '751525916');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('134', 'Marcus Casserfelt', '529682541');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('135', 'Carin Herrmann', '619363084');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('136', 'Rikard Engström', '1424148640');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('137', 'Johan Johansson', '550257494');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('138', 'Gunn Nylend Axthorne', '586276258');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('139', 'Patrik Potocki', '643612900');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('140', 'Henrik Adolfsson', '519007544');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('141', 'Pontus Bremdahl-Evanni', '1259238180');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('142', 'Tom McAlevey', '637041081');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('143', 'Susanna Landgren', '691805405');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('144', 'Sophie Wesslau', '800020530');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('145', 'Tomas Gerhardsen', '615241341');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('146', 'David Jonsson', '589336267');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('147', 'Therese Adeng%26%23229%3Brd', '741323690');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('148', 'Ludwig Jonsson', '579090042');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('149', 'Andrew Mager', '6205900');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('150', 'Patrick Juthberg', '605427404');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('152', 'Per Porserot', '818405640');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('153', 'Per Laxen', '538216124');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('154', 'Fredrik Rollman', '569096712');
INSERT INTO user (UserId, Name, FacebookId ) VALUES ('155', 'Emil Stenström', '727049967');